import Head from 'next/head'
import {useEffect} from "react";
import MainPageSlider from "@/components/MainPageSlider/MainPageSlider";
import MainPageFeatures from "@/components/MainPageFeatures/MainPageFeatures";
import MainPostSection from "@/components/MainPostSection/MainPostSection";
import MoreInfoSection from "@/components/MoreInfoSection/MoreInfoSection";
import CompanyServices from "@/components/CompanyServices/CompanyServices";
import Comments from "@/components/Comments/Comments";
import DetailsSection from "@/components/DetailsSection/DetailsSection";


export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <MainPageSlider></MainPageSlider>
                <MainPageFeatures></MainPageFeatures>
                <MainPostSection></MainPostSection>
                <MoreInfoSection></MoreInfoSection>
                <CompanyServices></CompanyServices>
                <Comments></Comments>
                <DetailsSection></DetailsSection>
            </main>
        </>
    )
}
